blank_issues_enabled: false
contact_links:
  - name: Sicherheitslücke melden / Report a security issue
    url: mailto:contact@voxellab.de
    about: Bitte nicht öffentlich posten, sondern per Mail / Please don't post publicly, send an email instead
